### ISSUE TITLE
Partial Match and No Match Fabrikate Components

### ISSUE THREAD

**Issue by andrewDoing** [andrewDoing/hydrate#29]
As a user I want to get suggestions of Fabrikate components that partially match deployments on my cluster. I also want my deployments that don't match a component to be reflected in my HLD, and perhaps create a Fabrikate Component Definition for it.

- [ ] Suggest Partial Match Components in #42 

- [ ] Create Subcomponent Entries for No Match Deployments in #41 

- [ ] Create Component for new Deployments in #43

**Comment by edaena** [comment]
@andrewDoing split this task
